### ISSUE TITLE
CovalentHQ - Fine-tune algorithm

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/NEARoracle-Oracle#17]
### Description 
Fine tune the algorithm, ensuring the output score is representative of the state of financial health of a user

### Tasks
- [x] generate multiple datasets for user profiles with different financial health status
- [x] compute a credit score for each of these users and compare the computed scores against your expected output
- [x] fine tune the model by altering the scalars in the `config.json` file
