### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/NEARoracle-Oracle#2]
#### Description
Design and implement identity branding for the NEARoracle DApp. Adopt the newly-created NEARoracle logo and design across **ALL** GitHub documentation

#### Tasks
 - [x] basic refactor to algo doc
 - [x] rebrand **all** README.md headers
 - [x] customize algorithm documentation to the NEAR Protocol use case
